### ISSUE TITLE
Add deprecation notice for non-default packages that have no keywords?

### ISSUE THREAD

**Issue by lee-dohm** [atom/deprecation-cop#32]
I don't know if this is really the right spot for this because this is more of recommending a best-practice than a deprecation. But it would allow users to urge package developers to add keywords to their packages through the Submit Issue framework.

**Comment by izuzak** [comment]
@lee-dohm I was thinking about this yesterday and while I like the idea of nudging users to add keywords, I'm not sure that using the deprecation cop for this is the best approach. I can see how package authors might be irritated by this (especially authors of popular packages with no keywords). Also, would be great if packages had a description as well, and not just keywords -- I definitely noticed at least one published package with no description. 

Sooooo, maybe we can think of some other ways to remind authors to add those things? Some ideas:

* add the `keywords` field to the templates so that it's there by default: https://github.com/atom/apm/tree/master/templates
* when publishing a new version of a package with apm, check if the package has keywords and a description. If not, log a warning to the console and let the user know (but we wouldn't fail the operation -- it would still succeed).

What do you think? :bulb:

**Comment by lee-dohm** [comment]
Yep, I totally see where you're coming from ...

I like both of your suggestions. One thing that has also been helpful for me to remember to work on deprecations is the deprecation listing in the GUI Spec Runner. I feel better that it catches me when I'm already working on the package ... rather than when I thought I was done or when I'm working on something else. Perhaps these nudges could be integrated there too?

**Comment by izuzak** [comment]
@lee-dohm I created https://github.com/atom/apm/issues/363 and https://github.com/atom/apm/issues/362 for those two ideas I mentioned above. :point_up: 

> One thing that has also been helpful for me to remember to work on deprecations is the deprecation listing in the GUI Spec Runner. I feel better that it catches me when I'm already working on the package ... rather than when I thought I was done or when I'm working on something else. Perhaps these nudges could be integrated there too?

Perhaps :smile: Recommendation: open a new issue and ask for more feedback (and maybe list some pros and cons?), and if the feedback looks positive -- consider opening a PR to add that ability. I think that's the best way to get answers. I don't have a strong opinion about it -- my gut reaction was that Atom is more concerned with how a package works, and apm is concerned with package metadata and the registry (which is why I though of adding the warning to apm in the first place). But again, that doesn't mean you shouldn't explore the idea further.

I'm going to close this since we discussed the original idea suggested in the issue. Thanks again for thinking about this stuff. :bow:
