### ISSUE TITLE
Not catching a deprecated API call in 0.52.0

### ISSUE THREAD

**Issue by impinball** [atom/deprecation-cop#52]
[`atom-html-preview` fails to load](https://github.com/webBoxio/atom-html-preview/issues/51), but when I ran Atom with `--include-deprecated-apis`, Deprecation Cop showed absolutely nothing. I can't tell exactly what API this fails to find, but it's near impossible to fix the broken package without knowing what broke.

Without flag:
![without flag](https://cloud.githubusercontent.com/assets/4483844/8027187/cab95464-0d60-11e5-9832-658c305d184f.png)

With flag:
![with flag](https://cloud.githubusercontent.com/assets/4483844/8027181/9cd3d894-0d60-11e5-9dc7-8059c35106d1.png)

**Comment by izuzak** [comment]
@impinball Thanks for the report -- I don't see anything wrong with that package either.

@benogle @kevinsawicki can you take a look? :pray: I _think_ this might be a false positive in [the list of deprecated packages](https://github.com/atom/atom/blob/master/build/deprecated-packages.json). :clipboard:

**Comment by benogle** [comment]
The deprecation may not be hit on startup, but this is what it's reporting: 

> Accessing PaneView via $::view() is deprecated. Use the raw DOM node or underlying model object instead.

https://gist.github.com/benogle/6d09e295c84b717ef9b4

**Comment by izuzak** [comment]
Thanks, @benogle. I think I see [the deprecation](https://github.com/webBoxio/atom-html-preview/blob/a8a7e7dc4bbc33584371daca4cadeb6133a4798c/lib/atom-html-preview-view.coffee#L57) from that repo now. I tried triggering that code path but wasn't able to (possibly another problem in the package), so that explains why I didn't notice the problem when I tried using the package.

I hope that helps, @impinball. :point_up:
