### ISSUE TITLE
Deprecation notice on Atom 1.13.0-beta5

### ISSUE THREAD

**Issue by rm-code** [atom/deprecation-cop#71]
I might need some help with updating my [ui-theme](https://github.com/rm-code/base16-ocean-dark-ui). 

Deprecation cop gives me a deprecation notice and points to index.less:
![screenshot 2016-11-27 20 33 55](https://cloud.githubusercontent.com/assets/11627131/20651198/e7c3fa4a-b4e0-11e6-8b96-8951f125d8c2.png)

I'm fairly sure I got rid of all the :host and ::shadow pseudo-selectors. Am I missing something?

**Comment by Ben3eeE** [comment]
Thanks for reaching out :grinning: Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
